insert into Founder(NAME, LAST_NAME, SECOND_LAST_NAME, SUMMARY, EMAIL, PASSWORD) values ('SEBAS','CUATEPOTZO','MARTINEZ','ASDFADF','SSTSCTM@GMAIL.COM','ADFADF');

insert into STATUS(STATUS_ID, NAME , DESCRIPTION) VALUES (0 ,'PUBLISHED','PUBLISHED POST');
insert into STATUS(STATUS_ID, NAME , DESCRIPTION) VALUES (1 ,'APPROVED', 'APPROVED POST TO BE PUBLISHED ');
insert into STATUS(STATUS_ID, NAME , DESCRIPTION) VALUES (2 ,'REVISION','REVISION POST');
insert into STATUS(STATUS_ID, NAME , DESCRIPTION) VALUES (3 ,'EDITION','EDITION COURSE');

insert into TYPE_POST (TYPE_POST_ID, NAME, DESCRIPTION) VALUES (0,'NEW','TECNOLOGY NEW'); 
insert into TYPE_POST (TYPE_POST_ID, NAME, DESCRIPTION) VALUES (1,'POST','TECNOLOGY POST'); 
insert into TYPE_POST (TYPE_POST_ID, NAME, DESCRIPTION) VALUES (2,'EXPERIENCE', 'FOUNDER EXPERIENCE'); 
insert into TYPE_POST (TYPE_POST_ID, NAME, DESCRIPTION) VALUES (3,'FOUNDER','FOUNDER BIOGRAPHY'); 
insert into TYPE_POST (TYPE_POST_ID, NAME, DESCRIPTION) VALUES (4,'PHILOSOPHY','GUTS & CODE PHILOSOPHY'); 
insert into TYPE_POST (TYPE_POST_ID, NAME, DESCRIPTION) VALUES (5, 'FUTURE','GUTS & CODE FUTURE'); 

insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST1',0,0,'TEST','2019-01-01',1,1,'2019-01-02', 1, 'POST 1', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST2',0,3,'TEST','2011-01-01',1,1,'2019-01-02', 1, 'POST 1', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST3',0,0,'TEST','2012-01-01',1,1,'2019-01-02', 1, 'POST 1', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST4',0,0,'TEST','2013-01-01',1,1,'2019-01-02', 1, 'POST 1', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST5',0,2,'TEST','2014-01-01',1,1,'2019-01-02', 1, 'POST 1', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST6',0,0,'TEST','2015-01-01',1,1,'2019-01-02', 1, 'POST 1', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST7',0,1,'TEST','2016-01-01',1,1,'2019-01-02', 1, 'POST 1', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST8',0,0,'TEST','2017-01-01',1,1,'2019-01-02', 1, 'POST 1', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST9',0,0,'TEST','2018-01-01',1,1,'2019-01-02', 1, 'POST 1', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST10',0,0,'TEST','2009-01-01',1,1,'2019-01-02', 1, 'POST 1', 'CDMX');