insert into Founder(NAME, LAST_NAME, SECOND_LAST_NAME, SUMMARY, EMAIL, PASSWORD) values ('SEBAS','CUATEPOTZO','MARTINEZ','ASDFADF','SSTSCTM@GMAIL.COM','ADFADF');

insert into STATUS(STATUS_ID, NAME , DESCRIPTION) VALUES (0 ,'PUBLISHED','PUBLISHED POST');
insert into STATUS(STATUS_ID, NAME , DESCRIPTION) VALUES (1 ,'APPROVED', 'APPROVED POST TO BE PUBLISHED ');
insert into STATUS(STATUS_ID, NAME , DESCRIPTION) VALUES (2 ,'REVISION','REVISION POST');
insert into STATUS(STATUS_ID, NAME , DESCRIPTION) VALUES (3 ,'EDITION','EDITION COURSE');

insert into TYPE_POST (TYPE_POST_ID, NAME, DESCRIPTION) VALUES (0,'NEW','TECNOLOGY NEW'); 
insert into TYPE_POST (TYPE_POST_ID, NAME, DESCRIPTION) VALUES (1,'POST','TECNOLOGY POST'); 
insert into TYPE_POST (TYPE_POST_ID, NAME, DESCRIPTION) VALUES (2,'EXPERIENCE', 'FOUNDER EXPERIENCE'); 
insert into TYPE_POST (TYPE_POST_ID, NAME, DESCRIPTION) VALUES (3,'FOUNDER','FOUNDER BIOGRAPHY'); 
insert into TYPE_POST (TYPE_POST_ID, NAME, DESCRIPTION) VALUES (4,'PHILOSOPHY','GUTS & CODE PHILOSOPHY'); 
insert into TYPE_POST (TYPE_POST_ID, NAME, DESCRIPTION) VALUES (5, 'FUTURE','GUTS & CODE FUTURE'); 

insert into TYPE_TEXT (TYPE_TEXT_ID, NAME, DESCRIPTION) VALUES (0,'HEADER','HEADER'); 
insert into TYPE_TEXT (TYPE_TEXT_ID, NAME, DESCRIPTION) VALUES (1,'BODY','BODY');
insert into TYPE_TEXT (TYPE_TEXT_ID, NAME, DESCRIPTION) VALUES (2,'FOOTER', 'FOOTER'); 
insert into TYPE_TEXT (TYPE_TEXT_ID, NAME, DESCRIPTION) VALUES (3,'ANOTATION','ANOTATION'); 

insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST10',0,0,'APPROVED','2009-01-01',1,1,'2019-01-02', 1, 'POST 10', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST11',0,0,'APPROVED','2019-02-01',1,1,'2019-02-02', 1, 'POST 11', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST12',0,3,'APPROVED','2011-03-01',1,1,'2019-03-02', 1, 'POST 12', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST13',0,0,'APPROVED','2012-04-01',1,1,'2019-04-02', 1, 'POST 13', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST14',0,0,'APPROVED','2013-05-01',1,1,'2019-05-02', 1, 'POST 14', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST0',0,0,'APPROVED','2009-01-01',1,1,'2019-01-02', 1, 'POST 15', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST1',0,0,'APPROVED','2019-02-01',1,1,'2019-02-02', 1, 'POST 16', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST2',0,3,'APPROVED','2011-03-01',1,1,'2019-03-02', 1, 'POST 17', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST3',0,0,'APPROVED','2012-04-01',1,1,'2019-04-02', 1, 'POST 18', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST4',0,0,'APPROVED','2013-05-01',1,1,'2019-05-02', 1, 'POST 19', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST15',0,2,'TEST','2014-06-01',1,1,'2019-06-02', 1, 'POST 15', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST16',0,0,'TEST','2015-07-01',1,1,'2019-07-02', 1, 'POST 16', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST17',0,1,'TEST','2016-08-01',1,1,'2019-08-02', 1, 'POST 17', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST18',0,0,'TEST','2017-09-01',1,1,'2019-09-02', 1, 'POST 18', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST19',0,0,'TEST','2018-10-01',1,1,'2019-10-02', 1, 'POST 19', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('POST20',0,0,'TEST','2009-11-01',1,1,'2019-11-02', 1, 'POST 20', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('NEW15',0,2,'TEST','2014-06-01',1,1,'2019-06-02', 0, 'NEW 15', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('NEW16',0,0,'TEST','2015-07-01',1,1,'2019-07-02', 0, 'NEW 16', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('NEW17',0,1,'TEST','2016-08-01',1,1,'2019-08-02', 0, 'NEW 17', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('NEW18',0,0,'TEST','2017-09-01',1,1,'2019-09-02', 0, 'NEW 18', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('NEW19',0,0,'TEST','2018-10-01',1,1,'2019-10-02', 0, 'NEW 19', 'CDMX');
insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION,) VALUES ('NEW20',0,0,'TEST','2009-11-01',1,1,'2019-11-02', 0, 'NEW 20', 'CDMX');

insert into TEXT (TEXT_ID,TYPE_TEXT_ID,POST_ID,TEXT_BETA,TEXT_REALIZE) VALUES (1,1,15,'Este es un texto muy muy largo', '');
insert into TEXT (TEXT_ID,TYPE_TEXT_ID,POST_ID,TEXT_BETA,TEXT_REALIZE) VALUES (2,0,15,'','Este es un texto muy muy largo');
insert into TEXT (TEXT_ID,TYPE_TEXT_ID,POST_ID,TEXT_BETA,TEXT_REALIZE) VALUES (3,2,15,'Este es un texto muy muy largo', 'Este es un texto muy muy largo');
insert into TEXT (TEXT_ID,TYPE_TEXT_ID,POST_ID,TEXT_BETA,TEXT_REALIZE) VALUES (4,1,14,'Este es un texto muy muy largo', '');
insert into TEXT (TEXT_ID,TYPE_TEXT_ID,POST_ID,TEXT_BETA,TEXT_REALIZE) VALUES (5,0,14,'','Este es un texto muy muy largo');
insert into TEXT (TEXT_ID,TYPE_TEXT_ID,POST_ID,TEXT_BETA,TEXT_REALIZE) VALUES (6,2,14,'Este es un texto muy muy largo', 'Este es un texto muy muy largo');

INSERT INTO IMAGE (IMAGE_ID,IMAGE_NAME,DESCRIPTION,IMAGE,TEXT_ID,FOOTER,CARDINALITY) VALUES('1', 'Java.png', 'Javas logo', FILE_READ('/opt/java.png'), 1, 'java', 'top');
INSERT INTO IMAGE (IMAGE_ID,IMAGE_NAME,DESCRIPTION,IMAGE,TEXT_ID,FOOTER,CARDINALITY) VALUES('2', 'Spring.png', 'Springs logo', FILE_READ('/opt/spring.png'), 2, 'spring', 'top');    
    