CREATE TABLE FOUNDER ( 
   FOUNDER_ID INT PRIMARY KEY auto_increment, 
   NAME VARCHAR(50) NOT NULL, 
   LAST_NAME VARCHAR(20) NOT NULL, 
   SECOND_LAST_NAME VARCHAR(20) NOT NULL,
   PHOTO BLOB,
   SUMMARY VARCHAR(200) NOT NULL,
   EMAIL VARCHAR(200) NOT NULL,
   PASSWORD VARCHAR(2000) NOT NULL
);

CREATE TABLE MESSAGE(
  MESSAGE_ID INT PRIMARY KEY auto_increment,
  MESSAGE_TEXT VARCHAR(100) NOT NULL,
  SENDER_ID INT NOT NULL,
  RECEIVER_ID INT NOT NULL,
  CLASSIFICATION VARCHAR(30) NOT null,
  DATE_RECEIVE DATE NOT NULL,
  STATUS BOOLEAN NOT NULL,
  foreign key (SENDER_ID) references FOUNDER(FOUNDER_ID),
  foreign key (RECEIVER_ID) references FOUNDER(FOUNDER_ID)
);