CREATE TABLE FOUNDER ( 
   FOUNDER_ID INT PRIMARY KEY auto_increment, 
   NAME VARCHAR(50) NOT NULL, 
   LAST_NAME VARCHAR(20) NOT NULL, 
   SECOND_LAST_NAME VARCHAR(20) NOT NULL,
   PHOTO BLOB,
   SUMMARY VARCHAR(200) NOT NULL,
   EMAIL VARCHAR(200) NOT NULL,
   PASSWORD VARCHAR(2000) NOT NULL
);

CREATE TABLE STATUS(
	STATUS_ID INT PRIMARY KEY auto_increment,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL
);

CREATE TABLE TYPE_POST(
	TYPE_POST_ID INT PRIMARY KEY auto_increment,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL
	);
	

CREATE TABLE POST(
	POST_ID INT PRIMARY KEY auto_increment,
	NAME VARCHAR(100) NOT NULL,
	NUMBER_VIEW INT NOT NULL,
	STATUS_ID INT not null,
	TOPIC VARCHAR(100) NOT NULL,
	LAST_UPDATE DATE ,
	WRITTER_ID INT NOT NULL,
	REVIEWER_ID INT NOT NULL,
	DATE_REVIEWER DATE,
	TYPE_POST_ID INT NOT NULL,
	TITLE VARCHAR(120) NOT NULL,
	LOCATION VARCHAR(100) NOT NULL,
	PARENT_ID INT ,
	IMAGE BLOB,
	CHILD_ID INT,
	foreign key (STATUS_ID) references STATUS(STATUS_ID),
	foreign key (WRITTER_ID) references FOUNDER(FOUNDER_ID),
	foreign key (REVIEWER_ID) references  FOUNDER(FOUNDER_ID),
	foreign key (TYPE_POST_ID) references TYPE_POST(TYPE_POST_ID),
	foreign key (PARENT_ID) references POST(POST_ID),
	foreign key (CHILD_ID) references POST(POST_ID)
);



CREATE TABLE MESSAGE(
  MESSAGE_ID INT PRIMARY KEY auto_increment,
  MESSAGE_TEXT VARCHAR(100) NOT NULL,
  SENDER_ID INT NOT NULL,
  RECEIVER_ID INT NOT NULL,
  CLASSIFICATION VARCHAR(30) NOT null,
  DATE_RECEIVE DATE NOT NULL,
  STATUS BOOLEAN NOT NULL,
  foreign key (SENDER_ID) references FOUNDER(FOUNDER_ID),
  foreign key (RECEIVER_ID) references FOUNDER(FOUNDER_ID)
);

