/*
CREATE DATABASE GutsNCode;

CREATE TABLE IF NOT EXISTS GutsNCode.FOUNDER (
	FOUNDER_ID BIGINT UNSIGNED auto_increment NOT NULL,
	NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    SUMMARY VARCHAR(1000) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    ALIAS VARCHAR(50) NOT NULL,
    PHOTO BLOB,
    CONSTRAINT FOUNDER_pk PRIMARY KEY (FOUNDER_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS GutsNCode.MESSAGE(
  MESSAGE_ID BIGINT UNSIGNED auto_increment NOT NULL,
  MESSAGE_TEXT VARCHAR(100) NOT NULL,
  SENDER_ID BIGINT UNSIGNED NOT NULL,
  RECEIVER_ID BIGINT UNSIGNED NOT NULL,
  CLASSIFICATION VARCHAR(30) NOT null,
  DATE_RECEIVE DATE NOT NULL,
  STATUS BOOLEAN NOT NULL,
  CONSTRAINT MESSAGE_pk PRIMARY KEY (MESSAGE_ID),
  CONSTRAINT SENDER_fk FOREIGN KEY (SENDER_ID) references FOUNDER(FOUNDER_ID) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT RECEIVER_fk FOREIGN KEY (RECEIVER_ID) references FOUNDER(FOUNDER_ID) ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS GutsNCode.STATUS(
	STATUS_ID BIGINT UNSIGNED auto_increment NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
    CONSTRAINT STATUS_pk PRIMARY KEY (STATUS_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS GutsNCode.IMAGE_OPTION(
	IMAGE_ID BIGINT UNSIGNED auto_increment NOT NULL,
	NAME VARCHAR(15) NOT NULL,
    CONSTRAINT IMAGE_pk PRIMARY KEY (IMAGE_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS GutsNCode.TYPE_POST(
	TYPE_POST_ID BIGINT UNSIGNED auto_increment NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
    CONSTRAINT TYPE_POST_pk PRIMARY KEY (TYPE_POST_ID)
	)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS GutsNCode.TYPE_TEXT(
	TYPE_TEXT_ID BIGINT UNSIGNED auto_increment NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
    CONSTRAINT TYPE_TEXT_pk PRIMARY KEY (TYPE_TEXT_ID)
	)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS GutsNCode.POST(
	POST_ID BIGINT UNSIGNED auto_increment NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	TOPIC VARCHAR(50) NOT NULL, 
	NUMBER_VIEW INTEGER UNSIGNED NOT NULL,
	STATUS_ID BIGINT UNSIGNED not null,
	TYPE_POST_ID BIGINT UNSIGNED NOT NULL,
	IMAGE_ID BIGINT UNSIGNED NOT NULL DEFAULT 1,
	LAST_UPDATE DATE NOT NULL,
	WRITTER_ID BIGINT UNSIGNED NOT NULL,
	REVIEWER_ID BIGINT UNSIGNED NOT NULL,
	DATE_REVIEWER DATE,
	LOCATION VARCHAR(50) NOT NULL,
	PARENT_ID BIGINT UNSIGNED NULL,
	CHILD_ID BIGINT UNSIGNED NULL,
	POST_EDIT_ID BIGINT UNSIGNED NULL,
    CONSTRAINT POST_pk PRIMARY KEY (POST_ID),
	CONSTRAINT STATUS_fk foreign key (STATUS_ID) references STATUS(STATUS_ID)  ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT WRITTER__fk foreign key (WRITTER_ID) references FOUNDER(FOUNDER_ID)  ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT REVIEWER_fk foreign key (REVIEWER_ID) references  FOUNDER(FOUNDER_ID)  ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT TYPE_POST_fk foreign key (TYPE_POST_ID) references TYPE_POST(TYPE_POST_ID)  ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT IMAGE_fk foreign key (IMAGE_ID) references IMAGE_OPTION(IMAGE_ID)  ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT PARENT_fk foreign key (PARENT_ID) references POST(POST_ID)  ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT CHILD_fk foreign key (CHILD_ID) references POST(POST_ID)  ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT POST_EDIT_fk foreign key (POST_EDIT_ID) references POST(POST_ID)  ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS GutsNCode.TEXT(
    TEXT_ID BIGINT UNSIGNED auto_increment NOT NULL,
    TYPE_TEXT_ID BIGINT UNSIGNED NOT NULL,
    POST_ID BIGINT UNSIGNED NOT NULL,
    TEXT_BETA VARCHAR(20000),
    TEXT_REALIZE VARCHAR(20000),
    CONSTRAINT TEXT_pk PRIMARY KEY (TEXT_ID),
    CONSTRAINT POST_fk foreign key (POST_ID) references POST(POST_ID),
    CONSTRAINT TYPE_TEXT_fk foreign key (TYPE_TEXT_ID) references TYPE_TEXT(TYPE_TEXT_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS GutsNCode.IMAGE(
    IMAGE_ID BIGINT UNSIGNED auto_increment NOT NULL,
    IMAGE_NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(50),
    IMAGE BLOB,
    TEXT_ID BIGINT UNSIGNED NOT NULL,
    FOOTER VARCHAR(100) NOT NULL,
    CARDINALITY VARCHAR(100) NOT NULL,
    CONSTRAINT IMAGE_pk PRIMARY KEY (IMAGE_ID),
    CONSTRAINT TEXT_fk foreign key (TEXT_ID) references TEXT(TEXT_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_spanish_ci;

create table IF NOT EXISTS GutsNCode.USERS(
	USERNAME VARCHAR(50) not null,
	PASSWORD VARCHAR(500) not null,
	EMAIL VARCHAR(100),
	ENABLED boolean not null,
	NUMBER_TRIES BIGINT not null default 0,
    CONSTRAINT FOUNDER_pk PRIMARY KEY (USERNAME)
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_spanish_ci;

create table IF NOT EXISTS GutsNCode.AUTHORITIES (
	USERNAME VARCHAR(50) not null,
	AUTHORITY VARCHAR(50) not null,
	constraint AUTHORITIES_FK foreign key(USERNAME) references USERS(USERNAME)
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS GutsNCode.STADISTICS(
    STAT_ID BIGINT UNSIGNED auto_increment NOT NULL,
    STAT_NAME VARCHAR(30) NOT NULL,
    STAT_VALUE VARCHAR(30) NOT NULL,
    STAT_DATE DATE NOT NULL,
    CONSTRAINT STAT_pk PRIMARY KEY (STAT_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_spanish_ci;

*/