-- insert into FOUNDER(NAME, LAST_NAME, SECOND_LAST_NAME, SUMMARY, EMAIL, PASSWORD, PHOTO) VALUES 
-- ('ABIGAIL','ORTEGA','VALDIVIA','Hola, soy Aby, me gusta estudiar','ABIGAILORTEGA31@GMAIL.COM','987654321',null),
-- ('SEBAS','CUATEPOTZO','MARTINEZ','Hola, soy Sebas, me gusta flojear','SSTSACM@GMAIL.COM','123456789', null)
-- ;
-- insert into STATUS(NAME , DESCRIPTION) VALUES
--   ('APPROVED', 'APPROVED POST TO BE PUBLISHED ')
-- , ('REVISION','REVISION POST')
-- , ('EDITION','EDITION COURSE')
-- , ('PUBLIAPPR','PUBLISHED AND APPROVED')
-- , ('PUBLIREV','PUBLISHED AND REVISION')
-- , ('PUBLIEDIT','PUBLISHED AND EDIT VERSION')
-- , ('PUBLISHED','PUBLISHED POST')
-- ;
-- insert into TYPE_POST(NAME, DESCRIPTION) VALUES 
--   ('POST','TECNOLOGY POST')
-- , ('EXPERIENCE', 'FOUNDER EXPERIENCE')
-- , ('FOUNDER','FOUNDER BIOGRAPHY')
-- , ('PHILOSOPHY','GUTS & CODE PHILOSOPHY')
-- , ('FUTURE','GUTS & CODE FUTURE')
-- , ('NEW','TECNOLOGY NEW')
-- ; 
-- insert into TYPE_TEXT (NAME, DESCRIPTION) VALUES  
--   ('BODY','BODY')
-- , ('FOOTER', 'FOOTER')
-- , ('ANOTATION','ANOTATION')
-- , ('HEADER','HEADER')
-- ; 
-- /*Entries for Post*/
-- insert into POST (POST_ID, NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION, IMAGE) VALUES
--   (1, 'JAVA POST 01',0,0,'java','3000-01-01',1,1,'3000-12-31', 1, 'JAVA POST 01', 'CDMX', null)
-- , (2, 'JAVA POST 02',0,0,'java','3000-01-01',1,1,'3000-12-31', 1, 'JAVA POST 02', 'CDMX', null)
-- , (3, 'JAVA POST 03',0,0,'java','3000-01-01',1,1,'3000-12-31', 1, 'JAVA POST 03', 'CDMX', null)
-- , (4, 'PARA APROVAR',0,1,'java','3000-01-01',1,1,'3000-12-31', 1, 'PARA APROVAR', 'CDMX', null)
-- ;
-- /**/
-- update POST set CHILD_ID = 2 where POST_ID = 1;
-- update POST set PARENT_ID = 1, CHILD_ID = 3 where POST_ID = 2;
-- update POST set PARENT_ID = 2 where POST_ID = 3;
-- /**/
-- insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION, IMAGE) VALUES
--   ('POST01',0,0,'spring','2020-11-01', 0,1,'2020-11-01', 1, 'POST 01', 'CDMX',null)
-- , ('POST02',0,0,'spring','2020-11-02', 0,1,'2020-11-02', 1, 'POST 02', 'CDMX',null)
-- , ('POST03',0,0,'spring','2020-11-03', 0,1,'2020-11-03', 1, 'POST 03', 'CDMX',null)
-- , ('POST04',0,0,'spring','2020-11-04', 0,1,'2020-11-04', 1, 'POST 04', 'CDMX',null)
-- , ('POST05',0,0,'spring','2020-11-05', 0,1,'2020-11-05', 1, 'POST 05', 'CDMX',null)
-- , ('POST06',0,0,'spring','2020-11-06', 0,1,'2020-11-06', 1, 'POST 06', 'CDMX',null)
-- , ('POST07',0,0,'spring','2020-11-07', 0,1,'2020-11-07', 1, 'POST 07', 'CDMX',null)
-- , ('POST08',0,0,'spring','2020-11-08', 0,1,'2020-11-08', 1, 'POST 08', 'CDMX',null)
-- , ('POST09',0,0,'spring','2020-11-09', 0,1,'2020-11-09', 1, 'POST 09', 'CDMX',null)
-- , ('POST10',0,0,'spring','2020-11-10', 0,1,'2020-11-10', 1, 'POST 10', 'CDMX',null)
-- , ('POST11',0,0,'spring','2020-11-11', 0,1,'2020-11-11', 1, 'POST 11', 'CDMX',null)
-- , ('POST12',0,0,'spring','2020-11-12', 0,1,'2020-11-12', 1, 'POST 12', 'CDMX',null)
-- , ('POST13',0,0,'spring','2020-11-13', 0,1,'2020-11-13', 1, 'POST 13', 'CDMX',null)
-- , ('POST14',0,0,'spring','2020-11-14', 0,1,'2020-11-14', 1, 'POST 14', 'CDMX',null)
-- , ('POST15',0,0,'spring','2020-11-15', 0,1,'2020-11-15', 1, 'POST 15', 'CDMX',null)
-- , ('POST16',0,0,'spring','2020-11-16', 0,1,'2020-11-16', 1, 'POST 16', 'CDMX',null)
-- , ('POST17',0,0,'spring','2020-11-17', 0,1,'2020-11-17', 1, 'POST 17', 'CDMX',null)
-- , ('POST18',0,0,'spring','2020-11-18', 0,1,'2020-11-18', 1, 'POST 18', 'CDMX',null)
-- , ('POST19',0,0,'spring','2020-11-19', 0,1,'2020-11-19', 1, 'POST 19', 'CDMX',null)
-- , ('POST20',0,0,'spring','2020-11-20', 0,1,'2020-11-20', 1, 'POST 20', 'CDMX',null)
-- , ('POST21',0,0,'java'  ,'2020-11-21', 0,1,'2020-11-21', 1, 'POST 21', 'CDMX',null)
-- , ('POST22',0,0,'java'  ,'2020-11-22', 0,1,'2020-11-22', 1, 'POST 22', 'CDMX',null)
-- , ('POST23',0,0,'java'  ,'2020-11-23', 0,1,'2020-11-23', 1, 'POST 23', 'CDMX',null)
-- , ('POST24',0,0,'java'  ,'2020-11-24', 0,1,'2020-11-24', 1, 'POST 24', 'CDMX',null)
-- , ('POST25',0,0,'java'  ,'2020-11-25', 0,1,'2020-11-25', 1, 'POST 25', 'CDMX',null)
-- , ('POST26',0,0,'devops','2020-11-26', 0,1,'2020-11-26', 1, 'POST 26', 'CDMX',null)
-- , ('POST27',0,0,'devops','2020-11-27', 0,1,'2020-11-27', 1, 'POST 27', 'CDMX',null)
-- , ('POST28',0,0,'devops','2020-11-28', 0,1,'2020-11-28', 1, 'POST 28', 'CDMX',null)
-- , ('POST29',0,0,'devops','2020-11-29', 0,1,'2020-11-29', 1, 'POST 29', 'CDMX',null)
-- , ('POST30',0,0,'devops','2020-11-30', 0,1,'2020-11-30', 1, 'POST 30', 'CDMX',null)
-- , ('POST31',0,2,'java'  ,'2020-12-01', 0,1,'2020-12-01', 1, 'POST 31', 'CDMX',null)
-- , ('POST32',0,2,'java'  ,'2020-12-02', 0,1,'2020-12-02', 1, 'POST 32', 'CDMX',null)
-- , ('POST33',0,2,'java'  ,'2020-12-03', 0,1,'2020-12-03', 1, 'POST 33', 'CDMX',null)
-- , ('POST34',0,2,'java'  ,'2020-12-04', 0,1,'2020-12-04', 1, 'POST 34', 'CDMX',null)
-- , ('POST35',0,2,'java'  ,'2020-12-05', 0,1,'2020-12-05', 1, 'POST 35', 'CDMX',null)
-- , ('POST36',0,2,'devops','2020-12-06', 0,1,'2020-12-06', 1, 'POST 36', 'CDMX',null)
-- , ('POST37',0,2,'devops','2020-12-07', 0,1,'2020-12-07', 1, 'POST 37', 'CDMX',null)
-- , ('POST38',0,2,'devops','2020-12-08', 0,1,'2020-12-08', 1, 'POST 38', 'CDMX',null)
-- , ('POST39',0,2,'devops','2020-12-09', 0,1,'2020-12-09', 1, 'POST 39', 'CDMX',null)
-- , ('POST40',0,2,'devops','2020-12-10', 0,1,'2020-12-10', 1, 'POST 40', 'CDMX',null)
-- ;
-- 
-- /*Entries for News*/
-- insert into POST (POST_ID, NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION, IMAGE) VALUES
--   (45,'Spring 01'   ,0,0,'spring','3000-01-01', 0,1,'3000-01-01', 0, 'Spring 01'   , 'CDMX',null)
-- , (46,'Spring 02'   ,0,0,'spring','3000-01-01', 0,1,'3000-01-01', 0, 'Spring 02'   , 'CDMX',null)
-- , (47,'Spring 03'   ,0,0,'spring','3000-01-01', 0,1,'3000-01-01', 0, 'Spring 03'   , 'CDMX',null)
-- , (48,'PARA APROVAR',0,1,'spring','3000-01-01', 0,1,'3000-01-01', 0, 'PARA APROVAR', 'CDMX',null)
-- ;
-- /**/
-- update POST set CHILD_ID = 46 where POST_ID = 45;
-- update POST set PARENT_ID = 45, CHILD_ID = 47 where POST_ID = 46;
-- update POST set PARENT_ID = 46 where POST_ID = 47;
-- /**/
-- insert into POST (NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION, IMAGE) VALUES
--   ('NEWS01',0,0,'kotlin' ,'2019-11-01', 0,1, '2019-11-01', 0, 'NEWS 01', 'CDMX',null)
-- , ('NEWS02',0,0,'kotlin' ,'2019-11-02', 0,1, '2019-11-02', 0, 'NEWS 02', 'CDMX',null)
-- , ('NEWS03',0,0,'kotlin' ,'2019-11-03', 0,1, '2019-11-03', 0, 'NEWS 03', 'CDMX',null)
-- , ('NEWS04',0,0,'kotlin' ,'2019-11-04', 0,1, '2019-11-04', 0, 'NEWS 04', 'CDMX',null)
-- , ('NEWS05',0,0,'kotlin' ,'2019-11-05', 0,1, '2019-11-05', 0, 'NEWS 05', 'CDMX',null)
-- , ('NEWS06',0,2,'kotlin' ,'2019-11-06', 0,1, '2019-11-06', 0, 'NEWS 06', 'CDMX',null)
-- , ('NEWS07',0,2,'kotlin' ,'2019-11-07', 0,1, '2019-11-07', 0, 'NEWS 07', 'CDMX',null)
-- , ('NEWS08',0,2,'kotlin' ,'2019-11-08', 0,1, '2019-11-08', 0, 'NEWS 08', 'CDMX',null)
-- , ('NEWS09',0,2,'kotlin' ,'2019-11-09', 0,1, '2019-11-09', 0, 'NEWS 09', 'CDMX',null)
-- , ('NEWS10',0,2,'kotlin' ,'2019-11-10', 0,1, '2019-11-10', 0, 'NEWS 10', 'CDMX',null)
-- , ('NEWS11',0,0,'graalvm','2019-11-11', 0,1, '2019-11-11', 0, 'NEWS 11', 'CDMX',null)
-- , ('NEWS12',0,0,'graalvm','2019-11-12', 0,1, '2019-11-12', 0, 'NEWS 12', 'CDMX',null)
-- , ('NEWS13',0,0,'graalvm','2019-11-13', 0,1, '2019-11-13', 0, 'NEWS 13', 'CDMX',null)
-- , ('NEWS14',0,0,'graalvm','2019-11-14', 0,1, '2019-11-14', 0, 'NEWS 14', 'CDMX',null)
-- , ('NEWS15',0,0,'graalvm','2019-11-15', 0,1, '2019-11-15', 0, 'NEWS 15', 'CDMX',null)
-- , ('NEWS16',0,2,'graalvm','2019-11-16', 0,1, '2019-11-16', 0, 'NEWS 16', 'CDMX',null)
-- , ('NEWS17',0,2,'graalvm','2019-11-17', 0,1, '2019-11-17', 0, 'NEWS 17', 'CDMX',null)
-- , ('NEWS18',0,2,'graalvm','2019-11-18', 0,1, '2019-11-18', 0, 'NEWS 18', 'CDMX',null)
-- , ('NEWS19',0,2,'graalvm','2019-11-19', 0,1, '2019-11-19', 0, 'NEWS 19', 'CDMX',null)
-- , ('NEWS20',0,2,'graalvm','2019-11-20', 0,1, '2019-11-20', 0, 'NEWS 20', 'CDMX',null)
-- , ('NEWS21',0,0,'apache' ,'2019-11-21', 0,1, '2019-11-21', 0, 'NEWS 21', 'CDMX',null)
-- , ('NEWS22',0,0,'apache' ,'2019-11-22', 0,1, '2019-11-22', 0, 'NEWS 22', 'CDMX',null)
-- , ('NEWS23',0,0,'apache' ,'2019-11-23', 0,1, '2019-11-23', 0, 'NEWS 23', 'CDMX',null)
-- , ('NEWS24',0,0,'apache' ,'2019-11-24', 0,1, '2019-11-24', 0, 'NEWS 24', 'CDMX',null)
-- , ('NEWS25',0,0,'apache' ,'2019-11-25', 0,1, '2019-11-25', 0, 'NEWS 25', 'CDMX',null)
-- , ('NEWS26',0,2,'apache' ,'2019-11-26', 0,1, '2019-11-26', 0, 'NEWS 26', 'CDMX',null)
-- , ('NEWS27',0,2,'apache' ,'2019-11-27', 0,1, '2019-11-27', 0, 'NEWS 27', 'CDMX',null)
-- , ('NEWS28',0,2,'apache' ,'2019-11-28', 0,1, '2019-11-28', 0, 'NEWS 28', 'CDMX',null)
-- , ('NEWS29',0,2,'apache' ,'2019-11-29', 0,1, '2019-11-29', 0, 'NEWS 29', 'CDMX',null)
-- , ('NEWS30',0,2,'apache' ,'2019-11-30', 0,1, '2019-11-30', 0, 'NEWS 30', 'CDMX',null)
-- , ('NEWS31',0,0,'java'   ,'2019-12-01', 0,1, '2019-12-01', 0, 'NEWS 31', 'CDMX',null)
-- , ('NEWS32',0,0,'java'   ,'2019-12-02', 0,1, '2019-12-02', 0, 'NEWS 32', 'CDMX',null)
-- , ('NEWS33',0,0,'java'   ,'2019-12-03', 0,1, '2019-12-03', 0, 'NEWS 33', 'CDMX',null)
-- , ('NEWS34',0,0,'java'   ,'2019-12-04', 0,1, '2019-12-04', 0, 'NEWS 34', 'CDMX',null)
-- , ('NEWS35',0,0,'java'   ,'2019-12-05', 0,1, '2019-12-05', 0, 'NEWS 35', 'CDMX',null)
-- , ('NEWS36',0,0,'spring' ,'2019-12-06', 0,1, '2019-12-06', 0, 'NEWS 36', 'CDMX',null)
-- , ('NEWS37',0,0,'spring' ,'2019-12-07', 0,1, '2019-12-07', 0, 'NEWS 37', 'CDMX',null)
-- , ('NEWS38',0,0,'spring' ,'2019-12-08', 0,1, '2019-12-08', 0, 'NEWS 38', 'CDMX',null)
-- , ('NEWS39',0,0,'spring' ,'2019-12-09', 0,1, '2019-12-09', 0, 'NEWS 39', 'CDMX',null)
-- , ('NEWS40',0,0,'spring' ,'2019-12-10', 0,1, '2019-12-10', 0, 'NEWS 40', 'CDMX',null)
-- ;
-- /*Text for Post*/
-- insert into TEXT (TEXT_ID,TYPE_TEXT_ID,POST_ID,TEXT_BETA,TEXT_REALIZE) VALUES 
--   (1,1,1,
--   	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo, ahora una cancion <br><br>Slip inside the eye of your mind <br> Dont you know you might find <br> A better place to play <br> You said that youd never been <br> But all the things that youve seen <br> Will slowly fade away <br> So I start a revolution from my bed <br> Cause you said the brains I had went to my head. <br> Step outside, summertimes in bloom <br> Stand up beside the fireplace <br> Take that look from off your face <br> You aint ever gonna burn my heart out <br> And so Sally can wait, she knows its too late as were walking on by <br> Her soul slides away, but dont look back in anger I heard you say <br> Take me to the place where you go <br> Where nobody knows if its night or day <br> But please dont put your life in the hands <br> Of a Rock n Roll band <br> Wholl throw it all away <br> Im gonna start a revolution from my bed <br> Cause you said the brains I had went to my head <br> Step outside cause summertimes in bloom <br> Stand up beside the fireplace <br> Take that look from off your face <br> Cause you aint ever gonna burn my heart out <br> So Sally can wait, she knows its too late as shes walking on by <br> My soul slides away, but dont look back in anger I heard you say <br> So Sally can wait, she knows its too late as were walking on by <br> Her soul slides away, but dont look back in anger I heard you say <br> So Sally can wait <br> She knows its too late as shes walking on by <br> My soul slides away <br> But dont look back in anger <br> Dont look back in anger <br> I heard you say <br> At least not today',
--   	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo, ahora una cancion <br><br>Slip inside the eye of your mind <br> Dont you know you might find <br> A better place to play <br> You said that youd never been <br> But all the things that youve seen <br> Will slowly fade away <br> So I start a revolution from my bed <br> Cause you said the brains I had went to my head. <br> Step outside, summertimes in bloom <br> Stand up beside the fireplace <br> Take that look from off your face <br> You aint ever gonna burn my heart out <br> And so Sally can wait, she knows its too late as were walking on by <br> Her soul slides away, but dont look back in anger I heard you say <br> Take me to the place where you go <br> Where nobody knows if its night or day <br> But please dont put your life in the hands <br> Of a Rock n Roll band <br> Wholl throw it all away <br> Im gonna start a revolution from my bed <br> Cause you said the brains I had went to my head <br> Step outside cause summertimes in bloom <br> Stand up beside the fireplace <br> Take that look from off your face <br> Cause you aint ever gonna burn my heart out <br> So Sally can wait, she knows its too late as shes walking on by <br> My soul slides away, but dont look back in anger I heard you say <br> So Sally can wait, she knows its too late as were walking on by <br> Her soul slides away, but dont look back in anger I heard you say <br> So Sally can wait <br> She knows its too late as shes walking on by <br> My soul slides away <br> But dont look back in anger <br> Dont look back in anger <br> I heard you say <br> At least not today')
-- , (2,0,1,'¿Quienes somos?','¿Quienes somos?')
-- , (3,2,1,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- , (4,3,1,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- 
-- , (5,1,2,
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo, ahora una cancion <br><br>Because of saving myself the hairdresser, <br>They cut wrong my hair today. <br>What am I going to do now? <br>This aint getting any better <br>My friends will make fun of me <br>I cant go back to school again <br>Not even with a different hairdo <br>This has not any improvement <br>Because of saving myself the hairdresser <br>Now I must wear a hat forever <br>My friens will make fun of me <br>I cant go to school anymore <br>His friends, we will make fun of him <br>He cant go back to school again <br>Theres just one comfort left for me <br>Wait for my hair to grow long again',
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo, ahora una cancion <br><br>Because of saving myself the hairdresser, <br>They cut wrong my hair today. <br>What am I going to do now? <br>This aint getting any better <br>My friends will make fun of me <br>I cant go back to school again <br>Not even with a different hairdo <br>This has not any improvement <br>Because of saving myself the hairdresser <br>Now I must wear a hat forever <br>My friens will make fun of me <br>I cant go to school anymore <br>His friends, we will make fun of him <br>He cant go back to school again <br>Theres just one comfort left for me <br>Wait for my hair to grow long again')
-- , (6,0,2,'¿Quienes somos?','¿Quienes somos?')
-- , (7,2,2,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- , (8,3,2,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- 
-- , (9,1,3,
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo, ahora una cancion <br><br>Hay perros que no ladran<br>Pero te lamen los huesos<br>Hay gatos que mahullan<br>Hasta exprimir su vientre<br>Hay gente que no ladra<br>Pero te exprime el alma<br>Hay gente que te odia<br>Pero te lame las manos así<br>Hay gente que no arriesga<br>Le tiene miedo a la muerte<br>Hay gatos que no mueren<br>Le dan la vuelta al cielo así<br>De noche todos los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>De noche todos los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>Hay perros que defienden<br>Hasta clavar colmillos<br>Perro que ladra<br>Perro que ladra no muerde<br>De noche todos los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>De noche todoso los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>Pardo me duermo, pardo te sueño<br>Pardo me duermo, pardo te sueño',
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo, ahora una cancion <br><br>Hay perros que no ladran<br>Pero te lamen los huesos<br>Hay gatos que mahullan<br>Hasta exprimir su vientre<br>Hay gente que no ladra<br>Pero te exprime el alma<br>Hay gente que te odia<br>Pero te lame las manos así<br>Hay gente que no arriesga<br>Le tiene miedo a la muerte<br>Hay gatos que no mueren<br>Le dan la vuelta al cielo así<br>De noche todos los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>De noche todos los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>Hay perros que defienden<br>Hasta clavar colmillos<br>Perro que ladra<br>Perro que ladra no muerde<br>De noche todos los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>De noche todoso los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>Pardo me duermo, pardo te sueño<br>Pardo me duermo, pardo te sueño')
-- , (10,0,3,'¿Quienes somos?','¿Quienes somos?')
-- , (11,2,3,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- , (12,3,3,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- ;
-- /*Text for News*/
-- insert into TEXT (TEXT_ID,TYPE_TEXT_ID,POST_ID,TEXT_BETA,TEXT_REALIZE) VALUES
--   (13,1,45,
--   	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo, ahora una cancion <br><br>Slip inside the eye of your mind <br> Dont you know you might find <br> A better place to play <br> You said that youd never been <br> But all the things that youve seen <br> Will slowly fade away <br> So I start a revolution from my bed <br> Cause you said the brains I had went to my head. <br> Step outside, summertimes in bloom <br> Stand up beside the fireplace <br> Take that look from off your face <br> You aint ever gonna burn my heart out <br> And so Sally can wait, she knows its too late as were walking on by <br> Her soul slides away, but dont look back in anger I heard you say <br> Take me to the place where you go <br> Where nobody knows if its night or day <br> But please dont put your life in the hands <br> Of a Rock n Roll band <br> Wholl throw it all away <br> Im gonna start a revolution from my bed <br> Cause you said the brains I had went to my head <br> Step outside cause summertimes in bloom <br> Stand up beside the fireplace <br> Take that look from off your face <br> Cause you aint ever gonna burn my heart out <br> So Sally can wait, she knows its too late as shes walking on by <br> My soul slides away, but dont look back in anger I heard you say <br> So Sally can wait, she knows its too late as were walking on by <br> Her soul slides away, but dont look back in anger I heard you say <br> So Sally can wait <br> She knows its too late as shes walking on by <br> My soul slides away <br> But dont look back in anger <br> Dont look back in anger <br> I heard you say <br> At least not today',
--   	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo, ahora una cancion <br><br>Slip inside the eye of your mind <br> Dont you know you might find <br> A better place to play <br> You said that youd never been <br> But all the things that youve seen <br> Will slowly fade away <br> So I start a revolution from my bed <br> Cause you said the brains I had went to my head. <br> Step outside, summertimes in bloom <br> Stand up beside the fireplace <br> Take that look from off your face <br> You aint ever gonna burn my heart out <br> And so Sally can wait, she knows its too late as were walking on by <br> Her soul slides away, but dont look back in anger I heard you say <br> Take me to the place where you go <br> Where nobody knows if its night or day <br> But please dont put your life in the hands <br> Of a Rock n Roll band <br> Wholl throw it all away <br> Im gonna start a revolution from my bed <br> Cause you said the brains I had went to my head <br> Step outside cause summertimes in bloom <br> Stand up beside the fireplace <br> Take that look from off your face <br> Cause you aint ever gonna burn my heart out <br> So Sally can wait, she knows its too late as shes walking on by <br> My soul slides away, but dont look back in anger I heard you say <br> So Sally can wait, she knows its too late as were walking on by <br> Her soul slides away, but dont look back in anger I heard you say <br> So Sally can wait <br> She knows its too late as shes walking on by <br> My soul slides away <br> But dont look back in anger <br> Dont look back in anger <br> I heard you say <br> At least not today')
-- , (14,0,45,'¿Quienes somos?','¿Quienes somos?')
-- , (15,2,45,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- , (16,3,45,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- 
-- , (17,1,46,
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo, ahora una cancion <br><br>Because of saving myself the hairdresser, <br>They cut wrong my hair today. <br>What am I going to do now? <br>This aint getting any better <br>My friends will make fun of me <br>I cant go back to school again <br>Not even with a different hairdo <br>This has not any improvement <br>Because of saving myself the hairdresser <br>Now I must wear a hat forever <br>My friens will make fun of me <br>I cant go to school anymore <br>His friends, we will make fun of him <br>He cant go back to school again <br>Theres just one comfort left for me <br>Wait for my hair to grow long again',
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo, ahora una cancion <br><br>Because of saving myself the hairdresser, <br>They cut wrong my hair today. <br>What am I going to do now? <br>This aint getting any better <br>My friends will make fun of me <br>I cant go back to school again <br>Not even with a different hairdo <br>This has not any improvement <br>Because of saving myself the hairdresser <br>Now I must wear a hat forever <br>My friens will make fun of me <br>I cant go to school anymore <br>His friends, we will make fun of him <br>He cant go back to school again <br>Theres just one comfort left for me <br>Wait for my hair to grow long again')
-- , (18,0,46,'¿Quienes somos?','¿Quienes somos?')
-- , (19,2,46,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- , (20,3,46,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- 
-- , (21,1,47,
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo, ahora una cancion <br><br>Hay perros que no ladran<br>Pero te lamen los huesos<br>Hay gatos que mahullan<br>Hasta exprimir su vientre<br>Hay gente que no ladra<br>Pero te exprime el alma<br>Hay gente que te odia<br>Pero te lame las manos así<br>Hay gente que no arriesga<br>Le tiene miedo a la muerte<br>Hay gatos que no mueren<br>Le dan la vuelta al cielo así<br>De noche todos los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>De noche todos los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>Hay perros que defienden<br>Hasta clavar colmillos<br>Perro que ladra<br>Perro que ladra no muerde<br>De noche todos los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>De noche todoso los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>Pardo me duermo, pardo te sueño<br>Pardo me duermo, pardo te sueño',
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo, ahora una cancion <br><br>Hay perros que no ladran<br>Pero te lamen los huesos<br>Hay gatos que mahullan<br>Hasta exprimir su vientre<br>Hay gente que no ladra<br>Pero te exprime el alma<br>Hay gente que te odia<br>Pero te lame las manos así<br>Hay gente que no arriesga<br>Le tiene miedo a la muerte<br>Hay gatos que no mueren<br>Le dan la vuelta al cielo así<br>De noche todos los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>De noche todos los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>Hay perros que defienden<br>Hasta clavar colmillos<br>Perro que ladra<br>Perro que ladra no muerde<br>De noche todos los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>De noche todoso los gatos son pardos<br>Pardo me duermo, pardo te sueño<br>Pardo me duermo, pardo te sueño<br>Pardo me duermo, pardo te sueño')
-- , (22,0,47,'¿Quienes somos?','¿Quienes somos?')
-- , (23,2,47,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- , (24,3,47,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- 
-- , (25,1,4,
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo',
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo')
-- , (26,0,4,'¿Quienes somos?','¿Quienes somos?')
-- , (27,2,4,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- , (28,3,4,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- 
-- , (29,1,48,
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo',
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo')
-- , (30,0,48,'¿Quienes somos?','¿Quienes somos?')
-- , (31,2,48,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- , (32,3,48,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- ;
-- /*Entries for Guts N Code*/
-- insert into POST (POST_ID, NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION, IMAGE) VALUES
--   (101,'ACERCA DE NOSOTROS',0,0,'gutsncode','2019-12-31',1,1,'2019-12-31',4,'ACERCA DE NOSOTROS','CDMX',null)
-- , (102,'FUNDADORES',0,0,'gutsncode','2019-12-31',1,1,'2019-12-31',3,'FUNDADORES','CDMX',null)
-- , (103,'EXPERIENCIAS',0,0,'gutsncode','2019-12-31',1,1,'2019-12-31',2,'EXPERIENCIAS','CDMX',null)
-- ;
-- 
-- insert into TEXT (TEXT_ID,TYPE_TEXT_ID,POST_ID,TEXT_BETA,TEXT_REALIZE) VALUES
-- /*Text for Acerca de Nosotros*/
--   (51,1,101,
--   'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo',
--   'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo')
-- , (52,0,101,'¿Quienes somos?','¿Quienes somos?')
-- , (53,2,101,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- , (54,3,101,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- 
-- /*Text for Fundadores*/
-- , (55,1,102,
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo',
-- 	'Hola, somos Aby y Sebas y somos los fundadores de Guts & Code, y creamos esta pagina para regañar a Sebas por flojo')
-- , (56,0,102,'¿Quienes somos?','¿Quienes somos?')
-- , (57,2,102,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- , (58,3,102,'Nos despendimos, y recuerden, Sebas es un flojo','Nos despendimos, y recuerden, Sebas es un flojo')
-- 
-- /*Text for Experiencias*/
-- , (59,1,103,
-- 	'Antes trabajabamos 20 horas al día, ahora solo 19, pues descubrimos que si existe la vida despues del trabajo',
-- 	'Antes trabajabamos 20 horas al día, ahora solo 19, pues descubrimos que si existe la vida despues del trabajo')
-- , (60,0,103,'De esclavos a Rockstars','De esclavos a Rockstars')
-- , (61,2,103,'A rockear bebes','A rockear bebes')
-- , (62,3,103,'A rockear bebes','A rockear bebes')
-- ;
-- 
-- /*Entries for Guts N Code*/
-- insert into POST (POST_ID, NAME, NUMBER_VIEW, STATUS_ID, TOPIC, LAST_UPDATE, WRITTER_ID, REVIEWER_ID, DATE_REVIEWER, TYPE_POST_ID, TITLE, LOCATION, IMAGE) VALUES
--   (104,'FUTURO'   ,0,0,'gutsncode','2019-12-31', 0,1, '2019-12-31', 5,'FUTURO','CDMX',null)
-- , (105,'FILOSOFIA',0,0,'gutsncode','2019-12-31', 0,1, '2019-12-31', 4,'FILOSOFIA','CDMX',null)
-- ;
-- 
-- /*Text for Fundadores*/
-- insert into TEXT (TEXT_ID,TYPE_TEXT_ID,POST_ID,TEXT_BETA,TEXT_REALIZE) VALUES
--   (63,1,104,'','Esperamos que nuestra pagina se llene de contenido de todo tipo, a modo que podamos ser un referente de conocimientos')
-- , (64,0,104,'','¿Quienes somos?')
-- , (65,2,104,'','Nos despendimos, y recuerden, Sebas es un flojo')
-- , (66,3,104,'','Nos despendimos, y recuerden, Sebas es un flojo')
-- 
-- /*Text for Experiencias*/
-- , (67,1,105,
-- 'Guts & Code nade del deseo de poder tener contenido de calidad de diferentes tecnologías en nuestra lengua materna, el Español. Creemos que las barreras del idioma no deben ser limitante para poder seguir desarrollandose dentro del mundo de la programación, en nuestro caso, más cercano a Java y las tecnologías que girán en torno a ella, aunque no nos limitamos solo a ella.
-- G&C se representa por un gato (que sobra decir que nos gustan los gatos) del cual compartimos estas cualidades y similitudes:
-- Agilidad
-- Curiosidad
-- Grandes cazadores.
-- Esperamos que podamos llegar a muchas personas deseosas como nosotros de apreder sobre el mundo de la programación con Java
-- ',
-- 'Guts & Code nade del deseo de poder tener contenido de calidad de diferentes tecnologías en nuestra lengua materna, el Español. Creemos que las barreras del idioma no deben ser limitante para poder seguir desarrollandose dentro del mundo de la programación, en nuestro caso, más cercano a Java y las tecnologías que girán en torno a ella, aunque no nos limitamos solo a ella.
-- G&C se representa por un gato (que sobra decir que nos gustan los gatos) del cual compartimos estas cualidades y similitudes:
-- Agilidad
-- Curiosidad
-- Grandes cazadores.
-- Esperamos que podamos llegar a muchas personas deseosas como nosotros de apreder sobre el mundo de la programación con Java
-- ')
-- , (68,0,105,'','Filosofia')
-- , (69,2,105,'','Conocenos')
-- , (70,3,105,'','Conocenos')
-- ;
-- 
-- /*
-- INSERT INTO IMAGE (IMAGE_ID,IMAGE_NAME,DESCRIPTION,IMAGE,TEXT_ID,FOOTER,CARDINALITY) VALUES
-- /*
--   (1, 'Java.png', 'Javas logo', null, 1, 'java', 'top')
-- , (2, 'Java.png', 'Javas logo', null, 4, 'java', 'top')
-- , (3, 'Java.png', 'Javas logo', null, 7, 'java', 'top')
-- , (4, 'Spring.png', 'Springs logo',null, 2, 'spring', 'top')
-- */
-- /*
--   (1, 'Java.png', 'Javas logo', FILE_READ('C:/opt/java.png'), 1, 'java', 'top')
-- , (2, 'Java.png', 'Javas logo', FILE_READ('C:/opt/java.png'), 4, 'java', 'top')
-- , (3, 'Java.png', 'Javas logo', FILE_READ('C:/opt/java.png'), 7, 'java', 'top')
-- , (4, 'Spring.png', 'Springs logo', FILE_READ('C:/opt/spring.png'), 2, 'spring', 'top')
-- ;
-- */
-- 
-- insert into USERS(username,password,enabled)
-- 	values('admin','$2a$10$hbxecwitQQ.dDT4JOFzQAulNySFwEpaFLw38jda6Td.Y/cOiRzDFu',true);
-- insert into AUTHORITIES(username,authority) 
-- 	values('admin','ROLE_ADMIN');

