select * from GutsNCode.FOUNDER;
select * from GutsNCode.STATUS;
select * from GutsNCode.TYPE_POST;
select * from GutsNCode.TYPE_TEXT;
select * from GutsNCode.IMAGE_OPTION;
select * from GutsNCode.POST;
select max(POST_ID) + 1 from GutsNCode.POST;
SELECT * FROM GutsNCode.FOUNDER where ALIAS != "sebas"
select * from GutsNCode.TEXT;
select * from GutsNCode.IMAGE;
select * from GutsNCode.USERS;
select * from GutsNCode.AUTHORITIES;
select * from GutsNCode.STADISTICS;
select * from GutsNCode.MESSAGE;

-- TRUNCATE TABLE GutsNCode.IMAGE;
-- TRUNCATE TABLE GutsNCode.STADISTICS;
-- TRUNCATE TABLE GutsNCode.MESSAGE;
-- TRUNCATE TABLE GutsNCode.TEXT;
-- TRUNCATE TABLE GutsNCode.POST;
-- TRUNCATE TABLE GutsNCode.IMAGE_OPTION;
-- TRUNCATE TABLE GutsNCode.TYPE_TEXT;
-- TRUNCATE TABLE GutsNCode.TYPE_POST;
-- TRUNCATE TABLE GutsNCode.STATUS;
-- TRUNCATE TABLE GutsNCode.AUTHORITIES;
-- TRUNCATE TABLE GutsNCode.USERS;
-- TRUNCATE TABLE GutsNCode.FOUNDER;
-- 
-- DROP TABLE GutsNCode.IMAGE;	
-- DROP TABLE GutsNCode.TEXT;
-- DROP TABLE GutsNCode.POST;
-- DROP TABLE GutsNCode.TYPE_TEXT;
-- DROP TABLE GutsNCode.TYPE_POST;
-- DROP TABLE GutsNCode.IMAGE_OPTION;
-- DROP TABLE GutsNCode.STATUS;
-- DROP TABLE GutsNCode.STADISTICS;
-- DROP TABLE GutsNCode.MESSAGE;
-- DROP TABLE GutsNCode.FOUNDER;
-- DROP TABLE GutsNCode.AUTHORITIES;
-- DROP TABLE GutsNCode.USERS;
