/*TRUNCATE TABLE GutsNCode.FOUNDER;
TRUNCATE TABLE GutsNCode.MESSAGE;
TRUNCATE TABLE GutsNCode.STATUS;
TRUNCATE TABLE GutsNCode.TYPE_POST;
TRUNCATE TABLE GutsNCode.TYPE_TEXT;
TRUNCATE TABLE GutsNCode.POST;
TRUNCATE TABLE GutsNCode.TEXT;
TRUNCATE TABLE GutsNCode.IMAGE;
TRUNCATE TABLE GutsNCode.USERS;
TRUNCATE TABLE GutsNCode.AUTHORITIES;
TRUNCATE TABLE GutsNCode.STADISTICS;
*/
/*
DROP TABLE GutsNCode.FOUNDER;
DROP TABLE GutsNCode.MESSAGE;
DROP TABLE GutsNCode.STATUS;
DROP TABLE GutsNCode.TYPE_POST;
DROP TABLE GutsNCode.TYPE_TEXT;
DROP TABLE GutsNCode.POST;
DROP TABLE GutsNCode.TEXT;
DROP TABLE GutsNCode.IMAGE;
DROP TABLE GutsNCode.USERS;
DROP TABLE GutsNCode.AUTHORITIES;
DROP TABLE GutsNCode.STADISTICS;
*/
